<?php

namespace AppBundle\Repository;

/**
 * SymfonyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymfonyRepository extends \Doctrine\ORM\EntityRepository
{
}
